import { StyleSheet } from 'react-native';
import { spacing, radii, typography } from '../../styles/theme';
import { scale, verticalScale, moderateScale } from '../../utils/responsive';

export const styles = StyleSheet.create({
  container: {
    padding: scale(20),
    maxWidth: scale(1000),
    width: '100%',
    alignSelf: 'center',
    paddingBottom: verticalScale(48),
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: verticalScale(20),
  },
  refreshButton: {
    width: scale(38),
    height: verticalScale(38),
    borderRadius: scale(6),
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  controlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(10),
    marginBottom: verticalScale(18),
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: scale(8),
    paddingHorizontal: scale(12),
    height: verticalScale(42),
  },
  projectDropdownBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: scale(8),
    paddingHorizontal: scale(12),
    height: verticalScale(42),
  },
  dropdownCard: {
    width: '100%',
    maxWidth: scale(380),
    borderRadius: radii.md,
    borderWidth: 1,
    overflow: 'hidden',
  },
  projectDropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: scale(14),
    paddingVertical: scale(10),
    borderRadius: scale(8),
    borderWidth: 1,
    marginBottom: verticalScale(4),
  },
  card: {
    padding: scale(18),
    marginBottom: verticalScale(14),
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: verticalScale(10),
  },
  envPill: {
    borderWidth: 1,
    paddingHorizontal: scale(6),
    paddingVertical: scale(2),
    borderRadius: scale(4),
  },
  threeDotBtn: {
    width: scale(32),
    height: verticalScale(32),
    borderRadius: scale(6),
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  urlsContainer: {
    gap: scale(6),
    marginBottom: verticalScale(12),
  },
  urlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  urlLabel: {
    width: scale(80),
    fontSize: moderateScale(12),
  },
  urlLinkTouch: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: scale(6),
  },
  miniIconBtn: {
    padding: scale(4),
    borderRadius: scale(4),
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: 'rgba(128, 128, 128, 0.15)',
    paddingTop: verticalScale(10),
    marginTop: verticalScale(4),
    flexWrap: 'wrap',
    gap: scale(8),
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: scale(16),
  },
  modalCard: {
    width: '100%',
    maxWidth: scale(440),
    borderRadius: radii.md,
    borderWidth: 1,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingHorizontal: scale(20),
    paddingVertical: scale(16),
    borderBottomWidth: 1,
  },
  menuActionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(20),
    paddingVertical: scale(12),
  },
  targetOption: {
    flex: 1,
    paddingVertical: scale(8),
    alignItems: 'center',
    borderRadius: scale(6),
    borderWidth: 1,
  },
  cacheToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: scale(12),
    borderRadius: scale(6),
    borderWidth: 1,
  },
  checkbox: {
    width: scale(20),
    height: verticalScale(20),
    borderRadius: scale(4),
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCancelBtn: {
    borderWidth: 1,
    borderRadius: scale(6),
    paddingHorizontal: scale(16),
    paddingVertical: scale(8),
  },
  modalSubmitBtn: {
    borderRadius: scale(6),
    paddingHorizontal: scale(18),
    paddingVertical: scale(8),
    minWidth: scale(80),
    alignItems: 'center',
    justifyContent: 'center',
  },
});

