import { StyleSheet, Platform } from "react-native";
import { spacing, radii, typography } from '../../styles/theme';
import { scale, verticalScale, moderateScale } from '../../utils/responsive';

export const styles = StyleSheet.create({
  staticPageContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: scale(20),
    paddingVertical: scale(20),
    overflow: "hidden",
  },
  projectPickerWrapper: {
    width: "100%",
    maxWidth: scale(420),
    maxHeight: verticalScale(600),
    height: "85%",
    alignItems: "center",
  },
  topIconBox: {
    width: scale(44),
    height: verticalScale(44),
    borderRadius: scale(10),
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: verticalScale(16),
  },
  mainTitle: {
    fontSize: moderateScale(20),
    letterSpacing: -0.4,
    textAlign: "center",
    marginBottom: verticalScale(6),
  },
  mainSubtitle: {
    fontSize: moderateScale(13),
    textAlign: "center",
    marginBottom: verticalScale(24),
  },
  searchBarWrapper: {
    width: "100%",
    height: verticalScale(44),
    borderWidth: 1,
    borderRadius: scale(8),
    paddingHorizontal: scale(14),
    justifyContent: "center",
    marginBottom: verticalScale(12),
  },
  searchBarInput: {
    fontSize: moderateScale(14),
    height: "100%",
  },
  scrollListContainer: {
    flex: 1,
    width: "100%",
    position: "relative",
    overflow: "hidden",
  },
  projectsScrollView: {
    flex: 1,
    width: "100%",
  },
  scrollContentList: {
    paddingBottom: verticalScale(90),
    gap: scale(4),
  },
  bottomFadeOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: verticalScale(100),
    pointerEvents: "none",
    zIndex: 10,
  },
  projectRowItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: scale(10),
    paddingHorizontal: scale(12),
    borderRadius: scale(8),
    gap: scale(12),
  },
  projectRowIcon: {
    width: scale(22),
    height: verticalScale(22),
    alignItems: "center",
    justifyContent: "center",
  },
  projectRowName: {
    fontSize: moderateScale(14),
    letterSpacing: -0.2,
  },
  container: {
    padding: scale(20),
    maxWidth: scale(960),
    width: "100%",
    alignSelf: "center",
    paddingBottom: verticalScale(48),
  },
  dashboardHeader: {
    flexDirection: Platform.OS === "web" ? "row" : "column",
    justifyContent: "space-between",
    alignItems: Platform.OS === "web" ? "center" : "flex-start",
    marginBottom: verticalScale(20),
    gap: scale(12),
  },
  backToProjectsBtn: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: scale(8),
    paddingHorizontal: scale(10),
    paddingVertical: scale(6),
  },
  projectTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: scale(12),
    flex: 1,
  },
  headerIconWrap: {
    width: scale(36),
    height: verticalScale(36),
    borderRadius: scale(8),
    alignItems: "center",
    justifyContent: "center",
  },
  switchProjectPill: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: scale(8),
    paddingHorizontal: scale(10),
    paddingVertical: scale(6),
  },
  liveBadge: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    paddingHorizontal: scale(8),
    paddingVertical: scale(2),
    borderRadius: radii.md,
    gap: scale(5),
    backgroundColor: "rgba(16, 185, 129, 0.12)",
    borderColor: "rgba(16, 185, 129, 0.25)",
  },
  liveDot: {
    width: scale(6),
    height: verticalScale(6),
    borderRadius: scale(3),
    backgroundColor: "#10B981",
  },
  liveText: {
    color: "#10B981",
    fontSize: moderateScale(11),
    fontWeight: "700",
  },
  controlRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "center",
    gap: scale(10),
    marginBottom: verticalScale(20),
  },
  timeRangeSelector: {
    flexDirection: "row",
    borderWidth: 1,
    borderRadius: scale(8),
    padding: scale(3),
  },
  timeRangeBtn: {
    paddingHorizontal: scale(12),
    paddingVertical: scale(5),
    borderRadius: scale(6),
  },
  metricToggle: {
    flexDirection: "row",
    borderWidth: 1,
    borderRadius: scale(8),
    padding: scale(3),
  },
  metricToggleBtn: {
    paddingHorizontal: scale(12),
    paddingVertical: scale(5),
    borderRadius: scale(6),
  },
  loadingContainer: {
    padding: scale(60),
    alignItems: "center",
    justifyContent: "center",
  },
  disabledCard: {
    padding: scale(36),
    alignItems: "center",
    justifyContent: "center",
    marginVertical: scale(12),
  },
  disabledIconWrap: {
    width: scale(64),
    height: verticalScale(64),
    borderRadius: scale(32),
    alignItems: "center",
    justifyContent: "center",
  },
  content: {
    gap: scale(20),
  },
  metricsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: scale(12),
  },
  metricCard: {
    flex: 1,
    minWidth: scale(160),
    padding: scale(16),
  },
  metricHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: verticalScale(4),
  },
  iconCircle: {
    width: scale(26),
    height: verticalScale(26),
    borderRadius: scale(13),
    alignItems: "center",
    justifyContent: "center",
  },
  chartCard: {
    padding: scale(18),
  },
  chartCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: verticalScale(16),
  },
  selectedTooltipPill: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: scale(6),
    paddingHorizontal: scale(8),
    paddingVertical: scale(4),
  },
  chartWrapper: {
    width: "100%",
  },
  chartXLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: scale(10),
    marginTop: verticalScale(6),
  },
  breakdownSection: {
    gap: scale(12),
  },
  breakdownHeader: {
    marginBottom: verticalScale(4),
  },
  tabsContainer: {
    flexDirection: "row",
    gap: scale(8),
    paddingBottom: verticalScale(4),
  },
  tabBtn: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: scale(8),
    paddingHorizontal: scale(12),
    paddingVertical: scale(7),
  },
  breakdownRow: {
    position: "relative",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: scale(16),
    paddingVertical: scale(12),
    overflow: "hidden",
  },
  relativeProgressFill: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
  },
});
