import { StyleSheet, Platform } from "react-native";
import { spacing, radii, typography } from '../../styles/theme';
import { scale, verticalScale, moderateScale } from '../../utils/responsive';

export const styles = StyleSheet.create({
  container: {
    padding: scale(24),
    maxWidth: scale(900),
    width: '100%',
    alignSelf: 'center',
    paddingBottom: verticalScale(64),
  },
  header: {
    marginBottom: verticalScale(28),
  },
  repoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: scale(16),
  },
  importButton: {
    borderWidth: 1,
    paddingHorizontal: scale(14),
    paddingVertical: scale(6),
    borderRadius: scale(6),
  },
  field: {
    marginBottom: verticalScale(16),
  },
  label: {
    fontSize: moderateScale(14),
  },
  autoBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    paddingHorizontal: scale(8),
    paddingVertical: scale(2),
    borderRadius: radii.md,
  },
  frameworkSelectorBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderRadius: scale(6),
    height: verticalScale(42),
    paddingHorizontal: scale(12),
  },
  envActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: scale(6),
    paddingHorizontal: scale(12),
    paddingVertical: scale(6),
  },
  rawEnvInput: {
    borderWidth: 1,
    borderRadius: scale(6),
    padding: scale(10),
    fontSize: moderateScale(12),
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    minHeight: verticalScale(80),
  },
  targetPill: {
    borderWidth: 1,
    borderRadius: scale(16),
    paddingHorizontal: scale(10),
    paddingVertical: scale(4),
  },
  addBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: scale(6),
    paddingHorizontal: scale(14),
    paddingVertical: scale(8),
  },
  envRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderRadius: scale(8),
    padding: scale(12),
    marginBottom: verticalScale(8),
  },
  errorCard: {
    borderWidth: 1,
    borderRadius: scale(10),
    padding: scale(16),
    marginBottom: verticalScale(24),
  },
  errorActionBtn: {
    borderWidth: 1,
    borderRadius: scale(6),
    paddingHorizontal: scale(12),
    paddingVertical: scale(6),
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: scale(16),
  },
  modalCard: {
    width: '100%',
    maxWidth: scale(440),
    borderRadius: radii.md,
    borderWidth: 1,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: scale(20),
    paddingVertical: scale(16),
    borderBottomWidth: 1,
  },
  frameworkOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: scale(12),
    borderRadius: scale(8),
    borderWidth: 1,
    marginBottom: verticalScale(6),
  },
});
