import { StyleSheet, Platform } from "react-native";
import { spacing, radii, typography } from '../../styles/theme';
import { scale, verticalScale, moderateScale } from '../../utils/responsive';

export const styles = StyleSheet.create({
  container: {
    padding: scale(20),
    maxWidth: scale(900),
    width: '100%',
    alignSelf: 'center',
    paddingBottom: verticalScale(48),
  },
  header: {
    flexDirection: Platform.OS === 'web' ? 'row' : 'column',
    justifyContent: 'space-between',
    alignItems: Platform.OS === 'web' ? 'center' : 'flex-start',
    marginBottom: verticalScale(24),
    gap: scale(12),
  },
  headerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(12),
    paddingVertical: scale(8),
    borderRadius: scale(6),
    borderWidth: 1,
  },
  failureBanner: {
    borderWidth: 1,
    borderRadius: scale(10),
    padding: scale(18),
    marginBottom: verticalScale(24),
  },
  errorCodePill: {
    borderWidth: 1,
    paddingHorizontal: scale(6),
    paddingVertical: scale(2),
    borderRadius: scale(4),
  },
  failureBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(14),
    paddingVertical: scale(8),
    borderRadius: scale(6),
  },
  failureBtnOutline: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(14),
    paddingVertical: scale(8),
    borderRadius: scale(6),
    borderWidth: 1,
  },
  promoteCard: {
    marginBottom: verticalScale(20),
    padding: scale(16),
  },
  promoteBtn: {
    paddingHorizontal: scale(16),
    paddingVertical: scale(8),
    borderRadius: scale(6),
  },
  targetBadge: {
    borderWidth: 1,
    paddingHorizontal: scale(8),
    paddingVertical: scale(2),
    borderRadius: scale(4),
  },
  timeline: {
    paddingVertical: scale(20),
    paddingHorizontal: scale(24),
    paddingLeft: scale(36),
  },
  timelineItem: {
    borderLeftWidth: 2,
    paddingLeft: scale(20),
    paddingBottom: verticalScale(28),
    position: 'relative',
  },
  icon: {
    position: 'absolute',
    left: scale(-12),
    top: 0,
  },
  timelineContent: {
    flex: 1,
    marginTop: verticalScale(-2),
  },
  timelineRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  metaGrid: {
    gap: scale(12),
  },
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: scale(16),
  },
  metaLabel: {
    width: scale(90),
    fontSize: moderateScale(13),
  },
  divider: {
    height: verticalScale(1),
  },
  actionRow: {
    flexDirection: 'row',
    gap: scale(12),
    alignItems: 'center',
  },
  livePublicBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: scale(16),
    borderRadius: scale(8),
    borderWidth: 1,
    marginBottom: verticalScale(20),
  },
  liveDot: {
    width: scale(10),
    height: verticalScale(10),
    borderRadius: scale(5),
  },
  visitLiveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(12),
    paddingVertical: scale(7),
    borderRadius: scale(6),
  },
  iconActionBtn: {
    height: verticalScale(44),
    width: scale(44),
    borderRadius: scale(6),
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  smallActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: scale(6),
    paddingHorizontal: scale(10),
    paddingVertical: scale(4),
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: scale(16),
  },
  modalCard: {
    width: '100%',
    maxWidth: scale(440),
    borderRadius: radii.md,
    borderWidth: 1,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: scale(20),
    paddingVertical: scale(16),
    borderBottomWidth: 1,
  },
  targetOption: {
    flex: 1,
    paddingVertical: scale(8),
    alignItems: 'center',
    borderRadius: scale(6),
    borderWidth: 1,
  },
  cacheToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: scale(12),
    borderRadius: scale(6),
    borderWidth: 1,
  },
  checkbox: {
    width: scale(20),
    height: verticalScale(20),
    borderRadius: scale(4),
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  aliasInput: {
    height: verticalScale(40),
    borderWidth: 1,
    borderRadius: scale(6),
    paddingHorizontal: scale(12),
    fontSize: moderateScale(13),
  },
  modalCancelBtn: {
    borderWidth: 1,
    borderRadius: scale(6),
    paddingHorizontal: scale(16),
    paddingVertical: scale(8),
  },
  modalSubmitBtn: {
    borderRadius: scale(6),
    paddingHorizontal: scale(18),
    paddingVertical: scale(8),
    minWidth: scale(80),
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    width: '100%',
  },
  infoLabel: {
    width: scale(110),
    flexShrink: 0,
  },
  infoValue: {
    flex: 1,
  },
});

